/** @type {import('tailwindcss').Config} */
// Ported from the approved inline CDN config (commit f37c9e7) so the static build matches 1:1.
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./services/**/*.html",
    "./areas-served/**/*.html",
    "./guides/**/*.html",
    "./resources/**/*.html",
    "./about/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1e",
        "on-surface": "#1a1c1e",
        "on-primary-fixed": "#00210a",
        "on-tertiary-fixed-variant": "#564500",
        "surface": "#f9f9fc",
        "tertiary-fixed-dim": "#edc200",
        "surface-container-highest": "#e2e2e5",
        "on-primary": "#ffffff",
        "surface-container": "#eeeef0",
        "on-secondary-container": "#5a2100",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbcc",
        "secondary-fixed-dim": "#ffb693",
        "primary-fixed-dim": "#71dc8a",
        "error": "#ba1a1a",
        "primary": "#00682f",
        "secondary-container": "#fe7119",
        "background": "#f9f9fc",
        "on-surface-variant": "#3e4a3e",
        "error-container": "#ffdad6",
        "outline": "#6e7a6e",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#7a3000",
        "inverse-primary": "#71dc8a",
        "surface-bright": "#f9f9fc",
        "on-secondary-fixed": "#351000",
        "surface-container-low": "#f3f3f6",
        "inverse-on-surface": "#f0f0f3",
        "surface-tint": "#006d31",
        "tertiary-container": "#cda700",
        "on-tertiary-container": "#4d3e00",
        "primary-container": "#00843d",
        "inverse-surface": "#2f3133",
        "surface-variant": "#e2e2e5",
        "secondary": "#a04100",
        "surface-container-high": "#e8e8ea",
        "tertiary": "#725c00",
        "tertiary-fixed": "#ffe07f",
        "on-primary-fixed-variant": "#005324",
        "on-primary-container": "#e7ffe6",
        "surface-dim": "#dadadc",
        "primary-fixed": "#8ef9a4",
        "outline-variant": "#bdcabb",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#231b00",
        "action-orange": "#fe7119",
        "trust-blue": "#0055A4",
        "tertiary-fixed-dim": "#edc200",
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "0.75rem", xl: "1rem", full: "9999px" },
      spacing: {
        "margin-mobile": "16px",
        "max-width": "1280px",
        "margin-desktop": "auto",
        "base": "8px",
        "gutter": "24px",
        "content-gap": "24px",
        "section-gap": "120px",
      },
      maxWidth: { "max-width": "1280px" },
      fontFamily: {
        "headline-md": ["Sora"],
        "body-lg": ["Hanken Grotesk"],
        "caption": ["Hanken Grotesk"],
        "display-lg": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Sora"],
        "label-bold": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
